// Copyright (c) 2023-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

package streaming

import (
	"github.com/mattermost/mattermost/server/public/model"
)

const RespondingToProp = "responding_to"
const NoRegen = "no_regen"
const UnsafeLinksPostProp = "unsafe_links"
const ConversationIDProp = "conversation_id"

// LLMRequesterUserIDProp is a compatibility bridge for the meeting summarization
// flow, which still produces custom_p2lab_agents_bot posts without a conversation entity.
// Ownership for conversation-backed posts should be resolved via ConversationIDProp
// and the conversation row's UserID; this prop should only be consulted as a
// fallback when no conversation_id is present. Remove once meeting flows migrate.
const LLMRequesterUserIDProp = "llm_requester_user_id"

// ModifyPostForBot modifies a post to add bot-specific properties
func ModifyPostForBot(botid string, requesterUserID string, post *model.Post, respondingToPostID string) {
	post.UserId = botid
	post.Type = "custom_p2lab_agents_bot" // This must be the only place we add this type for security.
	// This tags that the post has unsafe links since they could have been generated by a prompt injection.
	// This will prevent the server from making OpenGraph requests and markdown images being rendered.
	post.AddProp(UnsafeLinksPostProp, "true")

	// Compatibility bridge for meeting summarization posts that have no
	// conversation entity. Callers that do create a conversation overwrite
	// ownership via ConversationIDProp, so setting this unconditionally is safe.
	if requesterUserID != "" {
		post.AddProp(LLMRequesterUserIDProp, requesterUserID)
	}

	// Add the ID of the post we're responding to
	if respondingToPostID != "" {
		post.AddProp(RespondingToProp, respondingToPostID)
	}
}
